version: '3.8'
name: postgres

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME:-sample_db}
      - POSTGRES_USER=${DB_USER:-sample_user}
      - POSTGRES_PASSWORD=${DB_PW:-admin}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      -  ${DB_PORT:-5432}:5432
    # env_file:
    #   - ./environment/.env

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-sample@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:5050
    # env_file:
    #   - ./environment/.env

volumes:
  postgres_data:
  pgadmin_data: